name: p300_cnn
channels:
   - defaults
   - anaconda
   - conda-forge
dependencies:
   - python>=3.7
   - numpy
   - matplotlib
   - scikit-learn
   - cudatoolkit=10.0
   - cudnn
   - tensorflow-gpu==1.13.1